version: '3.8'

services:
  app:
    build:
      context: .
    depends_on: [neo4j]
    init: true
    environment:
      - VIRTUAL_HOST=editor.auohp.here
    expose:
      - '3000'
    networks:
      - default
      - nginx-proxy
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    secrets:
      - environment
  neo4j:
    image: neo4j:latest
    environment:
      - 'NEO4J_PLUGINS=["apoc", "n10s"]'
      - 'NEO4J_server_default__listen__address=0.0.0.0'
      - 'NEO4J_server_jvm_additional=-Dapoc.ttl.enabled=true'
      - 'NEO4J_server_jvm_additional=-Dapoc.uuid.enabled=true'
      - 'NEO4J_dbms_security_auth__enabled=false'
      - 'NEO4J_dbms_security_procedures_unrestricted=apoc.*'
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - type: volume
        source: graph_data
        target: /data

volumes:
  node_modules:
  graph_data:

secrets:
  environment:
    file: ./.env

networks:
  default:
  nginx-proxy:
    external: true
    name: nginx-proxy
