name: auohp
channels:
  - nvidia
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - python=3.10
  - huggingface_hub=0.24.2
  - numpy=1.26.4
  - spacy=3.7.5
  - poetry=1.8.3
  - pip:
    - 'git+https://github.com/m-bain/whisperx.git'
