name: auohp
channels:
  - pytorch
  - huggingface
  - conda-forge
dependencies:
  - click=8.1.7
  - huggingface_hub=0.24.2
  - numpy=1.26.4
  - pip=24.0
  - pkginfo=1.11.1
  - platformdirs=4.3.2
  - poetry=1.8.3
  - python=3.10
  - spacy=3.7.5
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - pip:
    - '--editable=git+https://github.com/m-bain/whisperx.git@main#egg=whisperx'
