compressionLevel: mixed

enableGlobalCache: false

initFields:
  version: 0.0.0
  author:
    email: contact@auohp.org
    name: ACT UP Oral History Project
    url: "https://auohp.org"
  license: GPL-3.0-or-later

initScope: auohp

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-tsconfig-references.cjs
    spec: "https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-tsconfig-references.js"

preferDeferredVersions: true

yarnPath: .yarn/releases/yarn-4.10.2.cjs
