services:
  app:
    build:
      context: .
    secrets:
      - source: environment
        mode: 0440
    expose:
      - '3030'
      - '4040'
    volumes:
      - type: bind
        source: .
        target: /app
  nginx:
    depends_on: [app]
    build:
      context: ./scripts/nginx
    ports:
      - '80:80'
      - '443:443'
secrets:
  environment:
    file: .env
