version: '3.8'

services:
  editor-proxy:
    image: marcnuri/port-forward
    environment:
      - VIRTUAL_HOST=editor.auohp.here
      - VIRTUAL_PORT=80
      - REMOTE_HOST=app
      - REMOTE_PORT=3030
    networks:
      - default
      - nginx-proxy
  app:
    build:
      context: .
    depends_on: [neo4j]
    expose:
      - '3030'
      - '4040'
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
      - type: volume
        source: app_modules
        target: /app/packages/caption-editor-app/node_modules
      - type: volume
        source: script_modules
        target: /app/packages/scripts/node_modules
    secrets:
      - environment
  neo4j:
    image: neo4j:5.13.0
    environment:
      - 'NEO4J_AUTH=neo4j/auohpauohp'
      - 'NEO4J_PLUGINS=["apoc", "apoc-extended"]'
      - 'NEO4J_server_default__listen__address=0.0.0.0'
      - 'NEO4J_server_jvm_additional=-Dapoc.ttl.enabled=true'
      - 'NEO4J_server_jvm_additional=-Dapoc.uuid.enabled=true'
      - 'NEO4J_dbms_ssl_policy_bolt_enabled=true'
      - 'NEO4J_dbms_ssl_policy_bolt_base__directory=/ssl'
      - 'NEO4J_dbms_ssl_policy_bolt_private__key__algorithm=EC'
      - 'NEO4J_dbms_ssl_policy_bolt_private__key__signature__algorithm=SHA256withECDSA'
      - 'NEO4J_dbms_ssl_policy_bolt_private__key=auohp.here.key'
      - 'NEO4J_dbms_ssl_policy_bolt_public__certificate=auohp.here.crt'
      - 'NEO4J_apoc_uuid_enabled=true'
      - 'NEO4J_apoc_uuid_refresh=30000'
      - 'NEO4J_dbms_security_procedures_unrestricted=apoc.*'
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - type: volume
        source: graph_data
        target: /data
      - type: bind
        source: ./scripts/neo4j
        target: /ssl

volumes:
  app_modules:
  graph_data:
  node_modules:
  script_modules:

secrets:
  environment:
    file: ./.env

networks:
  default:
  nginx-proxy:
    external: true
    name: nginx-proxy
