services:
  editor-proxy:
    image: phyllisstein/port-forward
    depends_on: [app]
    init: true
    environment:
      - VIRTUAL_HOST=editor.auohp.here
      - LOCAL_PORT=80
      - REMOTE_HOST=app
      - REMOTE_PORT=3030
    networks:
      - default
      - nginx-proxy
  search-component-proxy:
    image: phyllisstein/port-forward
    depends_on: [app]
    init: true
    environment:
      - VIRTUAL_HOST=search.auohp.here
      - LOCAL_PORT=80
      - REMOTE_HOST=app
      - REMOTE_PORT=4040
    networks:
      - default
      - nginx-proxy
  neo4j-bolt-proxy:
    image: phyllisstein/port-forward
    depends_on: [neo4j]
    init: true
    environment:
      - VIRTUAL_HOST=bolt.auohp.here
      - LOCAL_PORT=80
      - REMOTE_HOST=neo4j
      - REMOTE_PORT=7687
    networks:
      - default
      - nginx-proxy
  neo4j-http-proxy:
    image: marcnuri/port-forward
    depends_on: [neo4j]
    init: true
    environment:
      - VIRTUAL_HOST=neo4j.auohp.here
      - LOCAL_PORT=80
      - REMOTE_HOST=neo4j
      - REMOTE_PORT=7474
    networks:
      - default
      - nginx-proxy
  app:
    networks:
      - default
      - nginx-proxy
    build:
      context: .
      secrets:
        - source: environment
          mode: 0440
    depends_on: [neo4j]
    expose:
      - '3030'
      - '4040'
    ports:
      - '3030:3030'
      - '4040:4040'
    develop:
      watch:
        - path: packages/caption-editor-app
          target: /app/packages/caption-editor-app
          action: sync
          ignore:
            - node_modules/
        - path: packages/search-component
          target: /app/packages/search-component
          action: sync
          ignore:
            - node_modules/
        - path: packages/scripts
          target: /app/packages/scripts
          action: sync
        - action: rebuild
          path: yarn.lock

  neo4j:
    networks:
        - default
        - nginx-proxy
    image: neo4j:5.13.0
    environment:
      - 'NEO4J_AUTH=neo4j/auohpauohp'
      - 'NEO4J_PLUGINS=["apoc", "apoc-extended"]'
      - 'NEO4J_server_default__listen__address=0.0.0.0'
      - 'NEO4J_server_jvm_additional=-Dapoc.ttl.enabled=true'
      - 'NEO4J_server_jvm_additional=-Dapoc.uuid.enabled=true'
      - 'NEO4J_dbms_ssl_policy_bolt_enabled=true'
      - 'NEO4J_dbms_ssl_policy_bolt_base__directory=/ssl'
      - 'NEO4J_dbms_ssl_policy_bolt_private__key__algorithm=EC'
      - 'NEO4J_dbms_ssl_policy_bolt_private__key__signature__algorithm=SHA256withECDSA'
      - 'NEO4J_dbms_ssl_policy_bolt_private__key=auohp.here.key'
      - 'NEO4J_dbms_ssl_policy_bolt_public__certificate=auohp.here.crt'
      - 'NEO4J_apoc_uuid_enabled=true'
      - 'NEO4J_apoc_uuid_refresh=1000'
      - 'NEO4J_dbms_security_procedures_unrestricted=apoc.*'
    ports:
      - '7474:7474'
      - '7687:7687'
    expose:
      - '7474'
      - '7687'
    volumes:
      - type: volume
        source: graph_data
        target: /data
      - type: bind
        source: ./scripts/neo4j
        target: /ssl

volumes:
  graph_data:

secrets:
  environment:
    file: .env

networks:
  default:
  nginx-proxy:
    external: true
    name: nginx-proxy
