/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InterviewInterviewNumberRouteImport } from './routes/interview.$interviewNumber'

const InterviewInterviewNumberRoute =
  InterviewInterviewNumberRouteImport.update({
    id: '/interview/$interviewNumber',
    path: '/interview/$interviewNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/interview/$interviewNumber': typeof InterviewInterviewNumberRoute
}
export interface FileRoutesByTo {
  '/interview/$interviewNumber': typeof InterviewInterviewNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/interview/$interviewNumber': typeof InterviewInterviewNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/interview/$interviewNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/interview/$interviewNumber'
  id: '__root__' | '/interview/$interviewNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  InterviewInterviewNumberRoute: typeof InterviewInterviewNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/interview/$interviewNumber': {
      id: '/interview/$interviewNumber'
      path: '/interview/$interviewNumber'
      fullPath: '/interview/$interviewNumber'
      preLoaderRoute: typeof InterviewInterviewNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  InterviewInterviewNumberRoute: InterviewInterviewNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
