/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SearchRouteRouteImport } from "./routes/search/route";
import { Route as TranscriptRouteRouteImport } from "./routes/transcript/route";
import { Route as SearchResultsRouteRouteImport } from "./routes/search/results/route";
import { Route as TranscriptIndexRouteImport } from "./routes/transcript/index";
import { Route as TranscriptInterviewNumberRouteImport } from "./routes/transcript/$interviewNumber";
import { Route as TranscriptCreateRouteImport } from "./routes/transcript/create";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SearchRouteRoute = SearchRouteRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const TranscriptRouteRoute = TranscriptRouteRouteImport.update({
  id: "/transcript",
  path: "/transcript",
  getParentRoute: () => rootRouteImport,
} as any);
const SearchResultsRouteRoute = SearchResultsRouteRouteImport.update({
  id: "/results",
  path: "/results",
  getParentRoute: () => SearchRouteRoute,
} as any);
const TranscriptIndexRoute = TranscriptIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => TranscriptRouteRoute,
} as any);
const TranscriptInterviewNumberRoute =
  TranscriptInterviewNumberRouteImport.update({
    id: "/$interviewNumber",
    path: "/$interviewNumber",
    getParentRoute: () => TranscriptRouteRoute,
  } as any);
const TranscriptCreateRoute = TranscriptCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => TranscriptRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/search": typeof SearchRouteRouteWithChildren;
  "/transcript": typeof TranscriptRouteRouteWithChildren;
  "/search/results": typeof SearchResultsRouteRoute;
  "/transcript/$interviewNumber": typeof TranscriptInterviewNumberRoute;
  "/transcript/create": typeof TranscriptCreateRoute;
  "/transcript/": typeof TranscriptIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/search": typeof SearchRouteRouteWithChildren;
  "/search/results": typeof SearchResultsRouteRoute;
  "/transcript/$interviewNumber": typeof TranscriptInterviewNumberRoute;
  "/transcript/create": typeof TranscriptCreateRoute;
  "/transcript": typeof TranscriptIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/search": typeof SearchRouteRouteWithChildren;
  "/transcript": typeof TranscriptRouteRouteWithChildren;
  "/search/results": typeof SearchResultsRouteRoute;
  "/transcript/$interviewNumber": typeof TranscriptInterviewNumberRoute;
  "/transcript/create": typeof TranscriptCreateRoute;
  "/transcript/": typeof TranscriptIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/search"
    | "/transcript"
    | "/search/results"
    | "/transcript/$interviewNumber"
    | "/transcript/create"
    | "/transcript/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/search"
    | "/search/results"
    | "/transcript/$interviewNumber"
    | "/transcript/create"
    | "/transcript";
  id:
    | "__root__"
    | "/"
    | "/search"
    | "/transcript"
    | "/search/results"
    | "/transcript/$interviewNumber"
    | "/transcript/create"
    | "/transcript/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SearchRouteRoute: typeof SearchRouteRouteWithChildren;
  TranscriptRouteRoute: typeof TranscriptRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/transcript": {
      id: "/transcript";
      path: "/transcript";
      fullPath: "/transcript";
      preLoaderRoute: typeof TranscriptRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/search/results": {
      id: "/search/results";
      path: "/results";
      fullPath: "/search/results";
      preLoaderRoute: typeof SearchResultsRouteRouteImport;
      parentRoute: typeof SearchRouteRoute;
    };
    "/transcript/": {
      id: "/transcript/";
      path: "/";
      fullPath: "/transcript/";
      preLoaderRoute: typeof TranscriptIndexRouteImport;
      parentRoute: typeof TranscriptRouteRoute;
    };
    "/transcript/$interviewNumber": {
      id: "/transcript/$interviewNumber";
      path: "/$interviewNumber";
      fullPath: "/transcript/$interviewNumber";
      preLoaderRoute: typeof TranscriptInterviewNumberRouteImport;
      parentRoute: typeof TranscriptRouteRoute;
    };
    "/transcript/create": {
      id: "/transcript/create";
      path: "/create";
      fullPath: "/transcript/create";
      preLoaderRoute: typeof TranscriptCreateRouteImport;
      parentRoute: typeof TranscriptRouteRoute;
    };
  }
}

interface SearchRouteRouteChildren {
  SearchResultsRouteRoute: typeof SearchResultsRouteRoute;
}

const SearchRouteRouteChildren: SearchRouteRouteChildren = {
  SearchResultsRouteRoute: SearchResultsRouteRoute,
};

const SearchRouteRouteWithChildren = SearchRouteRoute._addFileChildren(
  SearchRouteRouteChildren,
);

interface TranscriptRouteRouteChildren {
  TranscriptInterviewNumberRoute: typeof TranscriptInterviewNumberRoute;
  TranscriptCreateRoute: typeof TranscriptCreateRoute;
  TranscriptIndexRoute: typeof TranscriptIndexRoute;
}

const TranscriptRouteRouteChildren: TranscriptRouteRouteChildren = {
  TranscriptInterviewNumberRoute: TranscriptInterviewNumberRoute,
  TranscriptCreateRoute: TranscriptCreateRoute,
  TranscriptIndexRoute: TranscriptIndexRoute,
};

const TranscriptRouteRouteWithChildren = TranscriptRouteRoute._addFileChildren(
  TranscriptRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRouteRoute: SearchRouteRouteWithChildren,
  TranscriptRouteRoute: TranscriptRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
