import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { nanoid } from 'nanoid'
import neo4j, { type EagerResult, int } from 'neo4j-driver'


const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)


const NEO4J_LABELS = [
    'Captions',
    'Child',
    'Interview',
    'Person',
    'Speaker',
    'Statement',
    'Transcript',
    'Video',
    'VTT',
]

const {
    NEO4J_PASSWORD = 'auohpauohp',
    NEO4J_URI = 'bolt+s://bolt.auohp.here:443',
    NEO4J_USERNAME = 'neo4j',
} = process.env
const neo4jDriver = neo4j.driver(
    NEO4J_URI,
    neo4j.auth.basic(NEO4J_USERNAME, NEO4J_PASSWORD),
    {
        disableLosslessIntegers: true,
    },
)


/**
 * Parse transcripts generated by OpenAI's Whisper model and seed a Neo4j
 * database. Transcript data is searchable at the level of the statement so that
 * the frontend can jump directly to the relevant point in a matching video.
 * Granular statement-level data is also expected to seed a knowledge graph.
 * Structured at the statement level, this, too, will intertwingle the
 * narratives of a wide slate of interviewees for a deep account of an event.
 *
 * Edits to the captions for correctness and style will be made against the data
 * model, from which the captions are generated. The data model is the source of
 * truth, and the captions are a derived artifact.
 */
async function seedInterview({ data, date, interviewee, interviewNumber, speakers, videoURL, vtt, vttURL }) {
    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            MATCH (jim:Person {name: 'Jim Hubbard'})
            MATCH (sarah:Person {name: 'Sarah Schulman'})
            WITH jim, sarah
            CREATE (i:Interview {number: $interviewNumber, date: date($date), uid: $interviewUID})
            CREATE (video:Video {url: $videoURL, uid: $videoUID})
            CREATE (vtt:VTT {text: $vtt, url: $vttURL, uid: $vttUID})
            CREATE (transcript:Transcript:Interview {uid: $transcriptUID})
            CREATE (interviewee:Person {name: $interviewee, uid: $intervieweeUID})
            CREATE (sarahSpeaker:Speaker:Interviewer {label: $speakers.sarah})
            CREATE (jimSpeaker:Speaker:Interviewer {label: $speakers.jim})
            CREATE (intervieweeSpeaker:Speaker:Interviewee {label: $speakers.interviewee})
            MERGE (interviewee)-[:INTERVIEWED_AS]->(intervieweeSpeaker)
            MERGE (jim)-[:INTERVIEWED_AS]->(jimSpeaker)
            MERGE (sarah)-[:INTERVIEWED_AS]->(sarahSpeaker)
            CREATE (transcript)-[:INCLUDES_SPEAKER]->(intervieweeSpeaker)
            CREATE (transcript)-[:INCLUDES_SPEAKER]->(jimSpeaker)
            CREATE (transcript)-[:INCLUDES_SPEAKER]->(sarahSpeaker)
            CREATE (i)-[:HAS_VIDEO]->(video)
            CREATE (video)-[:HAS_CAPTIONS]->(vtt)
            CREATE (video)-[:HAS_TRANSCRIPT]->(transcript)
        `, {
            date,
            interviewNumber: int(interviewNumber),
            transcriptUID: nanoid(),

            interviewee,
            speakers,
            interviewUID: nanoid(),
            intervieweeUID: nanoid(),

            videoUID: nanoid(),
            videoURL,
            vtt,
            vttURL,
            vttUID: nanoid(),
        },
    )

    for await (const chunk of data) {
        let result: EagerResult
        try {
            result = await neo4jDriver.executeQuery(
                // language=Cypher
                `
                    MATCH (interview:Interview {number: $interviewNumber}) -[:HAS_VIDEO]-> (video)
                    MATCH (video)-[:HAS_TRANSCRIPT]-> (transcript)
                    MATCH (transcript) -[:INCLUDES_SPEAKER]- (speaker:Speaker {label: $speaker})
                    MATCH (speaker) <-[:INTERVIEWED_AS]- (person:Person)
                    CREATE (speaker)-[:SAYS {startTime: $startTime, endTime: $endTime, startTimestamp: $startTimestamp, endTimestamp: $endTimestamp}]->(statement:Statement {text: $transcription})
                    RETURN statement, person, interview
                `, {
                    ...chunk,
                    speaker: chunk.speaker || speakers.interviewee,
                    interviewNumber: int(interviewNumber),
                },
            )
        } catch (error) {
            console.error(`
                Could not create node for segment starting ${ chunk.startTime } in interview
                ${ interviewNumber } for speaker ${ chunk.speaker }.

                ${ error.message }
            `)
        }
    }
}

async function seedVideo({ data, date, speakers, videoURL, vtt }) {
    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            MATCH (jim:Person {name: 'Jim Hubbard'})
            MATCH (sarah:Person {name: 'Sarah Schulman'})
            WITH jim, sarah
            CREATE (i:Interview {number: $interviewNumber, date: date($date), uid: $interviewUID})
            CREATE (video:Video {url: $videoURL, uid: $videoUID})
            CREATE (vtt:VTT {text: $vtt})
            CREATE (interviewee:Person {name: $interviewee, uid: $intervieweeUID})
            CREATE (sarahSpeaker:Speaker:Interviewer {label: $speakers.sarah})
            CREATE (jimSpeaker:Speaker:Interviewer {label: $speakers.jim})
            CREATE (intervieweeSpeaker:Speaker:Interviewee {label: $speakers.interviewee})
            MERGE (interviewee)-[:INTERVIEWED_AS]->(intervieweeSpeaker)
            MERGE (jim)-[:INTERVIEWED_AS]->(jimSpeaker)
            MERGE (sarah)-[:INTERVIEWED_AS]->(sarahSpeaker)
            CREATE (i)-[:INTERVIEWED_WITH]->(intervieweeSpeaker)
            CREATE (i)-[:INTERVIEWED_WITH]->(jimSpeaker)
            CREATE (i)-[:INTERVIEWED_WITH]->(sarahSpeaker)
            CREATE (i)-[:HAS_VIDEO]->(video)
            CREATE (i)-[:HAS_CAPTIONS]->(vtt)
        `, {
            date,
            interviewNumber: int(interviewNumber),

            interviewee,
            speakers,
            interviewUID: nanoid(),
            intervieweeUID: nanoid(),

            videoUID: nanoid(),
            videoURL,
            vtt,
        },
    )

    for await (const chunk of data) {
        let result: EagerResult
        try {
            result = await neo4jDriver.executeQuery(
                // language=Cypher
                `
                    MATCH (speaker:Speaker {label: $speaker}) <-[:INTERVIEWED_WITH]- (interview:Interview {number: $interviewNumber})
                    MATCH (speaker) <-[:INTERVIEWED_AS]- (person:Person)
                    MERGE (speaker)-[:SAYS {startTime: $startTime, endTime: $endTime}]->(statement)
                    RETURN statement, person, interview
                `, {
                    ...chunk,
                },
            )

            const wordPromises = chunk.words.map(async word => {
                await neo4jDriver.executeQuery(
                    // language=Cypher
                    `
                        MATCH (statement:Statement) <-[says:SAYS]- (speaker:Speaker)
                        WHERE says.startTime = $chunkStartTime AND says.endTime = $chunkEndTime
                        CREATE (statement)-[:SAYS {startTime: $word.startTime, endTime: $word.endTime}]->(w:Word {text: $word.word})
                        RETURN w
                    `,
                    {
                        word,
                        chunkStartTime: chunk.start,
                        chunkEndTime: chunk.end,
                    },
                )
            })

            await Promise.all(wordPromises)
        } catch (error) {
            console.error(`
                Could not create node for segment starting ${ chunk.startTime } in interview
                ${ interviewNumber } for speaker ${ chunk.speaker }.

                ${ result }
                ${ chunk }
            `)
        }
    }
}

async function bootstrap() {
    await neo4jDriver.getServerInfo()

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
          MATCH (n) DETACH DELETE n
        `,
    )

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
          DROP INDEX transcript_search IF EXISTS
        `,
    )

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
          DROP INDEX name_search IF EXISTS
        `,
    )

    for await (let label of NEO4J_LABELS) {
        await neo4jDriver.executeQuery(
            // language=Cypher
            `
                CREATE CONSTRAINT ${ label }UID IF NOT EXISTS
                FOR (n:${ label }) REQUIRE n.uid IS UNIQUE
            `,
            { label },
        )
    }

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            CREATE FULLTEXT INDEX transcript_search IF NOT EXISTS
            FOR (n:Statement) ON EACH [n.text]
        `)

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            CREATE (jim:Person {name: 'Jim Hubbard', uid: $jimUID})
            CREATE (sarah:Person {name: 'Sarah Schulman', uid: $sarahUID})
        `, { jimUID: nanoid(), sarahUID: nanoid() },
    )
}

async function main() {
    await bootstrap()


    let data, vtt


    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 025 - Lei Chou ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //
    data = JSON.parse(
        await fs.readFile(
            path.resolve(__dirname, '../assets/025_lei_chou/025_lei_chou.captions.json'),
            'utf8',
        ),
    )

    vtt = await fs.readFile(
        path.resolve(__dirname, '../assets/025_lei_chou/025_lei_chou.vtt'),
        'utf8',
    )

    await seedInterview({
        data,
        date: '2003-05-05',
        interviewee: 'Lei Chou',
        interviewNumber: 25,
        speakers: {
            interviewee: 'SPEAKER_01',
            jim: 'SPEAKER_03',
            sarah: 'SPEAKER_02',
        },
        videoURL: 'https://dyck.mobi/auohp/025_lei_chou.mp4',
        vtt,
        vttURL: 'https://dyck.mobi/auohp/025_lei_chou.vtt',
    })
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~ 027 - Ann Northrop ~~~~~~~~~~~~~~~~~~~~~~~~~~~ //
    data = JSON.parse(
        await fs.readFile(
            path.resolve(__dirname, '../assets/027_ann_northrop.captions.json'),
            'utf8',
        ),
    )

    vtt = await fs.readFile(
        path.resolve(__dirname, '../assets/027_ann_northrop.vtt'),
        'utf8',
    )

    await seedInterview({
        data,
        date: '2003-05-28',
        interviewee: 'Ann Northrop',
        interviewNumber: 27,
        speakers: {
            interviewee: 'SPEAKER_00',
            jim: 'SPEAKER_01',
            sarah: 'SPEAKER_02',
        },
        videoURL: 'https://dyck.mobi/auohp/027_ann_northrop.mp4',
        vtt,
        vttURL: 'https://dyck.mobi/auohp/027_ann_northrop.vtt',
    })
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~ 040 - Steve Quester ~~~~~~~~~~~~~~~~~~~~~~~~~~ //
    data = JSON.parse(
        await fs.readFile(
            path.resolve(__dirname, '../assets/040_steve_quester.captions.json'),
            'utf8',
        ),
    )

    vtt = await fs.readFile(
        path.resolve(__dirname, '../assets/040_steve_quester.vtt'),
        'utf8',
    )

    await seedInterview({
        data,
        date: '2004-01-17',
        interviewee: 'Steve Quester',
        interviewNumber: 40,
        speakers: {
            interviewee: 'SPEAKER_03',
            jim: 'SPEAKER_01',
            sarah: 'SPEAKER_05',
        },
        videoURL: 'https://dyck.mobi/auohp/040_steve_quester.mp4',
        vtt,
        vttURL: 'https://dyck.mobi/auohp/040_steve_quester.vtt',
    })
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //

    await neo4jDriver.close()
}

void (await main())
