import "dotenv/config";

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import * as R from "ramda";
import { nanoid } from "nanoid";
import neo4j, { type EagerResult, int } from "neo4j-driver";
import { stripIndent } from "common-tags";
import delay from "delay";


const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);


const NEO4J_LABELS = [
    "Broadsheet",
    "Documentary",
    "Interview",
    "Person",
    "Speaker",
    "Statement",
    "Transcript",
    "Video",
    "VTT",
];

const {
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    FILTER_INTERVIEWER_SPEAKER_HACK,
    NEO4J_PASSWORD,
    NEO4J_URI,
    NEO4J_USERNAME,
    OPENAI_API_KEY,
} = process.env;
const neo4jDriver = neo4j.driver(
    NEO4J_URI,
    neo4j.auth.basic(NEO4J_USERNAME, NEO4J_PASSWORD),
    {
        connectionTimeout: 2500,
        disableLosslessIntegers: true,
    },
);


/**
 * Parse transcripts generated by OpenAI's Whisper model and seed a Neo4j
 * database. Transcript data is searchable at the level of the statement so that
 * the frontend can jump directly to the relevant point in a matching video.
 * Granular statement-level data is also expected to seed a knowledge graph.
 * Structured at the statement level, this, too, will intertwingle the
 * narratives of a wide slate of interviewees for a deep account of an event.
 *
 * Edits to the captions for correctness and style will be made against the data
 * model, from which the captions are generated. The data model is the source of
 * truth, and the captions are a derived artifact.
 */
async function seedInterview({ data, date, interviewee, interviewNumber, jsonCaption, jsonCaptionURL, speakers, videoURL, vtt, vttURL }) {
    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            MATCH (jim:Person {name: 'Jim Hubbard'})
            MATCH (sarah:Person {name: 'Sarah Schulman'})
            WITH jim, sarah
            CREATE (i:Interview {number: $interviewNumber, date: date($date), uid: $interviewUID, interviewee: $interviewee})
            CREATE (video:Video:Asset {url: $videoURL, uid: $videoUID})
            CREATE (vtt:VTT:Caption {text: $vtt, url: $vttURL, uid: $vttUID})
            CREATE (json:JSON:Caption {text: $jsonCaption, url: $jsonCaptionURL, uid: $jsonCaptionUID})
            CREATE (transcript:Transcript {uid: $transcriptUID})
            CREATE (interviewee:Person {name: $interviewee, uid: $intervieweeUID})
            CREATE (sarahSpeaker:Speaker:Interviewer {label: $speakers.sarah})
            CREATE (jimSpeaker:Speaker:Interviewer {label: $speakers.jim})
            CREATE (intervieweeSpeaker:Speaker:Interviewee {label: $speakers.interviewee})
            MERGE (interviewee)-[:INTERVIEWED_AS]->(intervieweeSpeaker)
            MERGE (jim)-[:INTERVIEWED_AS]->(jimSpeaker)
            MERGE (sarah)-[:INTERVIEWED_AS]->(sarahSpeaker)
            CREATE (transcript)-[:INCLUDES_SPEAKER]->(intervieweeSpeaker)
            CREATE (transcript)-[:INCLUDES_SPEAKER]->(jimSpeaker)
            CREATE (transcript)-[:INCLUDES_SPEAKER]->(sarahSpeaker)
            CREATE (i)-[:HAS_ASSET]->(video)
            CREATE (video)-[:HAS_CAPTIONS]->(vtt)
            CREATE (video)-[:HAS_CAPTIONS]->(json)
            CREATE (i)-[:HAS_TRANSCRIPT]->(transcript)
        `, {
            date,
            interviewee,
            intervieweeUID: nanoid(),

            interviewNumber: int(interviewNumber),
            interviewUID: nanoid(),
            jsonCaption,
            jsonCaptionUID: nanoid(),

            jsonCaptionURL: vttURL,
            speakers,

            transcriptUID: nanoid(),
            videoUID: nanoid(),
            videoURL,

            vtt,
            vttUID: nanoid(),
            vttURL,
        },
    );

    const BATCH_SIZE = 100;
    let statementBatch = [];

    let segment = {
        children: [],
        endTime: null,
        endTimestamp: null,
        interviewNumber: int(interviewNumber),
        speaker: null,
        startTime: null,
        startTimestamp: null,
        statementUID: nanoid(),
        transcription: "",
        type: "segment",
        words: [],
    };

    const importBatch = async () => {
        if (FILTER_INTERVIEWER_SPEAKER_HACK && segment.speaker !== speakers.interviewee) {
            return;
        }

        try {
            // FIXME: Eliminate [:TRANSCRIBES] edge
            // FIXME: Times as DURATIONs
            //        https://neo4j.com/docs/cypher-manual/current/values-and-types/temporal/#cypher-temporal-durations
            await neo4jDriver.executeQuery(
                // language=Cypher
                `
                    MATCH (interview:Interview {number: $segment.interviewNumber})-[:HAS_TRANSCRIPT]-> (transcript)
                    MATCH (transcript) -[:INCLUDES_SPEAKER]-> (speaker:Speaker {label: $segment.speaker})
                    CREATE (segmentStatement:Statement {text: $segment.transcription, uid: $segment.statementUID})
                    CREATE (speaker) -[:SAYS {startTime: $segment.startTime, endTime: $segment.endTime}]-> (segmentStatement)
                    CREATE (transcript) -[:TRANSCRIBES {startTime: $segment.startTime, endTime: $segment.endTime}]-> (segmentStatement)
                    WITH segmentStatement
                    UNWIND $statementBatch AS chunk
                    CREATE (segmentStatement) -[:SAYS {startTime: chunk.startTime, endTime: chunk.endTime}]-> (caption:Caption {text: chunk.transcription, uid: chunk.statementUID})
                    RETURN count(caption)
                `, { segment, statementBatch },
            );
        } catch (error) {
            console.error(`
        Could not create batch statement at timestamp ${ segment.startTime }--${ segment.endTime }
        for speaker ${ segment.speaker } in interview ${ interviewNumber }.

        Error: ${ error }
      `);
        }
    };

    for await (const chunk of data) {
        if (segment.speaker !== chunk.speaker) {
            await importBatch();
            statementBatch = [];
            segment = {
                ...chunk,
                children: [],
                interviewNumber: int(interviewNumber),
                speaker: chunk.speaker || speakers.interviewee,
                statementUID: nanoid(),
                transcription: "",
                words: [],
            };
        }

        segment.endTimestamp = chunk.endTimestamp;
        segment.endTime = chunk.endTime;
        segment.transcription += ` ${ chunk.transcription }`;

        statementBatch.push({
            ...chunk,
            interviewNumber: int(interviewNumber),
            speaker: chunk.speaker || speakers.interviewee,
            statementUID: nanoid(),
        });
    }

    if (statementBatch.length) {
        await importBatch();
    }
}

async function bootstrap() {
    await neo4jDriver.getServerInfo();

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            MATCH (n) DETACH DELETE n
        `,
    );

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            DROP INDEX transcript_search IF EXISTS
        `,
    );

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            DROP INDEX name_search IF EXISTS
        `,
    );

    for await (let label of NEO4J_LABELS) {
        await neo4jDriver.executeQuery(
            // language=Cypher
            `
                CREATE CONSTRAINT ${ label }UID IF NOT EXISTS
                FOR (n:${ label }) REQUIRE n.uid IS UNIQUE
            `, { label },
        );
    }

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            CREATE FULLTEXT INDEX transcript_search IF NOT EXISTS
            FOR (s:Statement) ON EACH [s.text]
        `,
    );

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            CREATE FULLTEXT INDEX name_search IF NOT EXISTS
            FOR (p:Person) ON EACH [p.name]
        `,
    );

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            CREATE (jim:Person {name: 'Jim Hubbard', uid: $jimUID})
            CREATE (sarah:Person {name: 'Sarah Schulman', uid: $sarahUID})
            CREATE (:Committee:Collective {name: 'Gran Fury', uid: $gfUID})
        `, { gfUID: nanoid(), jimUID: nanoid(), sarahUID: nanoid() },
    );
}

async function seedAllInterviews() {
    let data, vtt, jsonCaption;


    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 025 - Lei Chou ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //
    data = JSON.parse(
        await fs.readFile(
            path.resolve(__dirname, "../assets/025_lei_chou.json"),
            "utf8",
        ),
    );

    jsonCaption = await fs.readFile(
        path.resolve(__dirname, "../assets/025_lei_chou.json"),
        "utf8",
    );

    vtt = await fs.readFile(
        path.resolve(__dirname, "../assets/025_lei_chou.vtt"),
        "utf8",
    );

    await seedInterview({
        data,
        date: "2003-05-05",
        interviewee: "Lei Chou",
        interviewNumber: 25,
        jsonCaption,
        jsonCaptionURL: "https://dyck.mobi/auohp/025_lei_chou.json",
        speakers: {
            interviewee: "SPEAKER_01",
            jim: "SPEAKER_03",
            sarah: "SPEAKER_02",
        },
        videoURL: "https://dyck.mobi/auohp/025_lei_chou.mp4",
        vtt,
        vttURL: "https://dyck.mobi/auohp/025_lei_chou.vtt",
    });
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //

    // ~~~~~~~~~~~~~~~~~~~~~~~~ 064 - Vincent Gagliostro ~~~~~~~~~~~~~~~~~~~~~~~~ //
    data = JSON.parse(
        await fs.readFile(
            path.resolve(__dirname, "../assets/064_vincent_gagliostro.json"),
            "utf8",
        ),
    );

    jsonCaption = await fs.readFile(
        path.resolve(__dirname, "../assets/064_vincent_gagliostro.json"),
        "utf8",
    );

    vtt = await fs.readFile(
        path.resolve(__dirname, "../assets/064_vincent_gagliostro.vtt"),
        "utf8",
    );

    await seedInterview({
        data,
        date: "2005-07-08",
        interviewee: "Vincent Gagliostro",
        interviewNumber: 64,
        jsonCaption,
        jsonCaptionURL: "https://dyck.mobi/auohp/064_vincent_gagliostro.json",
        speakers: {
            interviewee: "SPEAKER_00",
            jim: "SPEAKER_01",
            sarah: "SPEAKER_02",
        },
        videoURL: "https://dyck.mobi/auohp/064_vincent_gagliostro.mp4",
        vtt,
        vttURL: "https://dyck.mobi/auohp/064_vincent_gagliostro.vtt",
    });
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~ 082 - David Robinson ~~~~~~~~~~~~~~~~~~~~~~~~~~ //
    data = JSON.parse(
        await fs.readFile(
            path.resolve(__dirname, "../assets/082_david_robinson.json"),
            "utf8",
        ),
    );

    jsonCaption = await fs.readFile(
        path.resolve(__dirname, "../assets/082_david_robinson.json"),
        "utf8",
    );

    vtt = await fs.readFile(
        path.resolve(__dirname, "../assets/082_david_robinson.vtt"),
        "utf8",
    );

    await seedInterview({
        data,
        date: "2007-07-16",
        interviewee: "David Robinson",
        interviewNumber: 82,
        jsonCaption,
        jsonCaptionURL: "https://dyck.mobi/auohp/082_david_robinson.json",
        speakers: {
            interviewee: "SPEAKER_03",
            jim: "SPEAKER_00",
            sarah: "SPEAKER_01",
        },
        videoURL: "https://dyck.mobi/auohp/082_david_robinson.mp4",
        vtt,
        vttURL: "https://dyck.mobi/auohp/082_david_robinson.vtt",
    });
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 087 - Jill Harris ~~~~~~~~~~~~~~~~~~~~~~~~~~~ //
    data = JSON.parse(
        await fs.readFile(
            path.resolve(__dirname, "../assets/087_jill_harris.json"),
            "utf8",
        ),
    );

    jsonCaption = await fs.readFile(
        path.resolve(__dirname, "../assets/087_jill_harris.json"),
        "utf8",
    );

    vtt = await fs.readFile(
        path.resolve(__dirname, "../assets/087_jill_harris.vtt"),
        "utf8",
    );

    await seedInterview({
        data,
        date: "2008-06-27",
        interviewee: "Jill Harris",
        interviewNumber: 87,
        jsonCaption,
        jsonCaptionURL: "https://dyck.mobi/auohp/087_jill_harris.json",
        speakers: {
            interviewee: "SPEAKER_02",
            jim: "SPEAKER_01",
            sarah: "SPEAKER_04",
        },
        videoURL: "https://dyck.mobi/auohp/087_jill_harris.mp4",
        vtt,
        vttURL: "https://dyck.mobi/auohp/087_jill_harris.vtt",
    });
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~ 117 - Alexis Danzig ~~~~~~~~~~~~~~~~~~~~~~~~~~ //
    data = JSON.parse(
        await fs.readFile(
            path.resolve(__dirname, "../assets/117_alexis_danzig.json"),
            "utf8",
        ),
    );

    jsonCaption = await fs.readFile(
        path.resolve(__dirname, "../assets/117_alexis_danzig.json"),
        "utf8",
    );

    vtt = await fs.readFile(
        path.resolve(__dirname, "../assets/117_alexis_danzig.vtt"),
        "utf8",
    );

    await seedInterview({
        data,
        date: "2004-01-17",
        interviewee: "Alexis Danzig",
        interviewNumber: 117,
        jsonCaption,
        jsonCaptionURL: "https://dyck.mobi/auohp/117_alexis_danzig.json",
        speakers: {
            interviewee: "SPEAKER_01",
            jim: "SPEAKER_00",
            sarah: "SPEAKER_02",
        },
        videoURL: "https://dyck.mobi/auohp/117_alexis_danzig.mp4",
        vtt,
        vttURL: "https://dyck.mobi/auohp/117_alexis_danzig.vtt",
    });
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 119 - Mary Cotter ~~~~~~~~~~~~~~~~~~~~~~~~~~~ //
    data = JSON.parse(
        await fs.readFile(
            path.resolve(__dirname, "../assets/119_mary_cotter.json"),
            "utf8",
        ),
    );

    jsonCaption = await fs.readFile(
        path.resolve(__dirname, "../assets/119_mary_cotter.json"),
        "utf8",
    );

    vtt = await fs.readFile(
        path.resolve(__dirname, "../assets/119_mary_cotter.vtt"),
        "utf8",
    );

    await seedInterview({
        data,
        date: "2010-06-23",
        interviewee: "Mary Cotter",
        interviewNumber: 119,
        jsonCaption,
        jsonCaptionURL: "https://dyck.mobi/auohp/119_mary_cotter.json",
        speakers: {
            interviewee: "SPEAKER_00",
            jim: "SPEAKER_01",
            sarah: "SPEAKER_02",
        },
        videoURL: "https://dyck.mobi/auohp/119_mary_cotter.mp4",
        vtt,
        vttURL: "https://dyck.mobi/auohp/119_mary_cotter.vtt",
    });
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //
}

async function seedStopChurch() {
    const broadsheetUID = nanoid();
    const stopChurchUID = nanoid();
    const transcriptUID = nanoid();

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            CREATE (stopChurch:Action {uid: $stopChurchUID, name: $stopChurchName, date: date($stopChurchDate)})
            CREATE (broadsheet:Broadsheet {uid: $broadsheetUID, title: $broadsheetTitle})
            CREATE (broadsheet)-[:HAS_ASSET]->(image:Image:Asset {url: $imageURL})
            CREATE (broadsheet)-[:MENTIONS]->(stopChurch)
            CREATE (stopChurch)-[:HAS_BROADSHEET]->(broadsheet)
            RETURN stopChurch, broadsheet
        `, {
            broadsheetTitle: "Stop This Man",
            broadsheetUID,
            imageURL: "https://dyck.mobi/auohp/stopchurch-gigapixel-recovery-quality-4x.png",
            stopChurchDate: "1989-12-10",
            stopChurchName: "Stop the Church",
            stopChurchUID,
        },
    );

    // FIXME: :Statement is a clumsy way to think about the text of a broadsheet.
    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            MATCH (broadsheet:Broadsheet {uid: $broadsheetUID})
            CREATE (broadsheet)-[:HAS_TRANSCRIPT]->(transcript:Transcript {uid: $transcriptUID})
            CREATE (transcript)-[:TRANSCRIBES]->(statement:Statement {text: $transcription, uid: $statementUID})
            RETURN statement
        `, {
            broadsheetUID,
            statementUID: nanoid(),
            transcription: stripIndent`
                STOP THE CHURCH
                Massive protest
                Sunday December 10
                9:30am
                St. Patrick's Cathedral
                5th Avenue & 50th Street
                Fight its opposition to abortion.
                Fight its murderous AIDS policy.
                Take direct action.
                Take control of your body.
            `,
            transcriptUID,
        },
    );
}

async function seedAshesAction() {
    let data, vtt, jsonCaption;


    data = JSON.parse(
        await fs.readFile(
            path.resolve(__dirname, "../assets/the_ashes_action.json"),
            "utf8",
        ),
    );

    jsonCaption = await fs.readFile(
        path.resolve(__dirname, "../assets/the_ashes_action.json"),
        "utf8",
    );

    vtt = await fs.readFile(
        path.resolve(__dirname, "../assets/the_ashes_action.vtt"),
        "utf8",
    );

    const actionUID = nanoid();
    const documentaryUID = nanoid();
    const videoUID = nanoid();
    const transcriptUID = nanoid();
    const vttUID = nanoid();

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            CREATE (doc:Documentary:Film {uid: $documentaryUID, title: $documentaryTitle, date: date($documentaryDate), slug: $documentarySlug})
            CREATE (video:Video:Asset {url: $videoURL, uid: $videoUID})
            CREATE (vtt:VTT:Captions {text: $vtt, url: $vttURL, uid: $vttUID})
            CREATE (json:JSON:Captions {text: $jsonCaption, url: $jsonCaptionURL, uid: $jsonCaptionUID})
            CREATE (transcript:Transcript {uid: $transcriptUID})
            CREATE (doc)-[:HAS_ASSET]->(video)
            CREATE (video)-[:HAS_CAPTIONS]->(vtt)
            CREATE (video)-[:HAS_CAPTIONS]->(json)
            CREATE (doc)-[:HAS_TRANSCRIPT]->(transcript)
        `, {
            documentaryDate: "1992-10-11",
            documentarySlug: "ashes-action",
            documentaryTitle: "The Ashes Action",
            documentaryUID,

            jsonCaption,

            jsonCaptionUID: nanoid(),
            jsonCaptionURL: "https://dyck.mobi/auohp/the_ashes_action.json",

            transcriptUID,
            videoUID,
            videoURL: "https://dyck.mobi/auohp/the_ashes_action.mp4",

            vtt,
            vttUID,
            vttURL: "https://dyck.mobi/auohp/the_ashes_action.vtt",
        },
    );

    const allSpeakers = new Set();
    for (const chunk of data) {
        allSpeakers.add(chunk.speaker);
    }

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            UNWIND $speakers AS speaker
            MATCH (doc:Documentary {uid: $documentaryUID}) -[:HAS_TRANSCRIPT]-> (transcript {uid: $transcriptUID})
            CREATE (transcript)-[:INCLUDES_SPEAKER]->(s:Speaker {label: speaker})
            RETURN s
        `, { documentaryUID, speakers: Array.from(allSpeakers), transcriptUID },
    );

    await neo4jDriver.executeQuery(
        `
            MATCH (doc:Documentary {uid: $documentaryUID}) -[:HAS_TRANSCRIPT]-> (transcript) -[:INCLUDES_SPEAKER]-> (drSpeaker:Speaker {label: 'SPEAKER_02'})
            MATCH (dr:Person {name: 'David Robinson'})
            CREATE (dr)-[:INTERVIEWED_AS]->(drSpeaker)
        `, { documentaryUID },
    );

    for await (const chunk of data) {
        let result: EagerResult;
        try {
            result = await neo4jDriver.executeQuery(
                // language=Cypher
                `
                    MATCH (transcript {uid: $transcriptUID}) -[:INCLUDES_SPEAKER]-> (speaker:Speaker {label: $speaker})
                    CREATE (transcript)-[:TRANSCRIBES {startTime: $startTime, endTime: $endTime}]->(statement:Statement {text: $transcription, uid: $statementUID})
                    CREATE (speaker)-[:SAYS]->(statement)
                    RETURN statement, speaker
                `, {
                    ...chunk,
                    statementUID: nanoid(),
                    transcriptUID,
                },
            );
        } catch (error) {
            console.error(`
        Could not create node for segment starting ${ chunk.startTime } in video
        ${ documentaryUID } for speaker ${ chunk.speaker }.
      `);
        }
    }

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            MATCH (doc:Documentary {uid: $documentaryUID})
            CREATE (aa:Action {uid: $actionUID, name: $actionName, date: date($actionDate)})
            CREATE (aa)-[:HAS_DOCUMENTARY]->(doc)
            CREATE (doc)-[:MENTIONS]->(aa)
        `, {
            actionDate: "1992-10-11",
            actionName: "The Ashes Action",
            actionUID,
            documentaryUID,
        },
    );

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            MATCH (aa:Action {uid: $actionUID})
            MATCH (gf:Collective {name: 'Gran Fury'})
            CREATE (broadsheet:Broadsheet {uid: $broadsheetUID, title: $broadsheetTitle})-[:MENTIONS]->(aa)
            CREATE (aa)-[:HAS_BROADSHEET]->(broadsheet)
            CREATE (broadsheet)-[:HAS_ASSET]->(image:Image:Asset {url: $imageURL, uid: $imageUID})
            CREATE (broadsheet)-[:HAS_TRANSCRIPT]->(transcript:Transcript {uid: $transcriptUID})
            CREATE (transcript)-[:TRANSCRIBES]->(statement:Statement {text: $transcription, uid: $statementUID})
            CREATE (gf)-[:DESIGNS]->(broadsheet)
        `, {
            actionUID,
            broadsheetTitle: "White House Urn",
            broadsheetUID: nanoid(),
            imageUID: nanoid(),
            imageURL: "https://dyck.mobi/auohp/synAshes_flyer-gigapixel-recovery-quality-4x-fs8.png",
            statementUID: nanoid(),
            transcription: stripIndent`
                You have lost someone to AIDS. For more than a decade, your government has
                mocked your loss. You have spoken out in anger, joined political protests,
                carried fake coffins and mock tombstones, and splattered red paint to represent
                someone's HIV-positive blood, perhaps your own. George Bush believes that the
                White House gates shield him, from you, your loss, and his responsibility for
                the AIDS crisis. Now it is time to bring AIDS home to George Bush. On October
                11th, we will carry the actual ashes of people we love in funeral procession to
                the White House. In an act of grief and rage and love, we will deposit their
                ashes on the White House lawn.

                Join us to protest twelve years of genocidal AIDS policy.
            `,
            transcriptUID: nanoid(),
        },
    );
}

async function seedDemoEdges() {
    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            MATCH (stt:Action {name: 'Stop the Church'})
            MERGE (vince:Statement {text: 'Stop the church was a phrase that was met to a lot of objection.'}) -[:MENTIONS]-> (stt)
            MERGE (alexis:Statement {text: ' stop the church, for example.'}) -[:MENTIONS]-> (stt)
            MERGE (ashes:Statement {text: 'I want you to remember that stop the church is pretty easy to convince people about what an evil group of perverts we are, right?'}) -[:MENTIONS]-> (stt)
            RETURN vince, alexis, ashes, stt
        `,
    );

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            MATCH (s:Statement {text: 'So we did the ashes action in October of 92.'}),
                    (a:Action {name: 'The Ashes Action'})
            MERGE (s) -[:MENTIONS]-> (a)
            RETURN s, a
        `,
    );
}

async function seedVectorIndex() {
    const BATCH_SIZE = 10;
    let batch = [];
    const importBatch = async () => {
        const toEncode = R.pluck("text", batch);
        await neo4jDriver.executeQuery(
            // language=Cypher
            `
                CALL genai.vector.encodeBatch(
                    $toEncode,
                    'Bedrock',
                    {
                        accessKeyId: $accessKeyId,
                        secretAccessKey: $secretAccessKey,
                        model: 'amazon.titan-embed-text-v1'
                    }
                ) YIELD index, vector
                MATCH (s:Statement {uid: $batch[index].uid})
                CALL db.create.setNodeVectorProperty(s, 'embedding', vector)
        `, {
                accessKeyId: AWS_ACCESS_KEY_ID,
                secretAccessKey: AWS_SECRET_ACCESS_KEY,
                batch,
                toEncode,
            },
        );
    };

    // FIXME: Instead of filtering out interviewer questions and breaking
    // accessibility when generating captions, we should filter out interviewer
    // questions when generating the vector index.
    const statements = await neo4jDriver.executeQuery(`
        MATCH (s:Statement)
        RETURN s.uid AS uid, s.text AS text
    `);

    for (const statement of statements.records) {
        const { text, uid } = statement.toObject();
        batch.push({ text, uid });
        if (batch.length === BATCH_SIZE) {
            await importBatch();
            console.log(`Imported ${ BATCH_SIZE } statements (paused 500ms)`);
            await delay(500);
            batch = [];
        }
    }
    if (batch.length) {
        await importBatch();
    }

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            CREATE VECTOR INDEX statement_embedding IF NOT EXISTS
            FOR (s:Statement) ON s.embedding
            OPTIONS {indexConfig: {
                \`vector.dimensions\`: 1024,
                \`vector.similarity_function\`: 'cosine'
            }}
        `,
    );
}

async function main() {
    await bootstrap();

    await seedAllInterviews();
    await seedAshesAction();
    await seedStopChurch();
    await seedDemoEdges();
    // await seedVectorIndex();

    await neo4jDriver.close();
}

void (await main());
