import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { nanoid } from 'nanoid'
import neo4j, { type EagerResult, int } from 'neo4j-driver'


const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)


const NEO4J_LABELS = [
    'Captions',
    'Interview',
    'Person',
    'Speaker',
    'Statement',
    'Video',
    'WordTimings',
]

const {
    NEO4J_PASSWORD = 'auohpauohp',
    NEO4J_URI = 'bolt://127.0.0.1:7687',
    NEO4J_USERNAME = 'neo4j',
} = process.env
const neo4jDriver = neo4j.driver(
    NEO4J_URI,
    neo4j.auth.basic(NEO4J_USERNAME, NEO4J_PASSWORD),
    {
        disableLosslessIntegers: true,
    },
)


function chunkBySpeaker(segments) {
    let chunkedSegments = [segments[0]]

    for (let i = 1; i < segments.length; i++) {
        const segment = segments[i]
        const lastSegment = chunkedSegments[chunkedSegments.length - 1]

        if (lastSegment?.speaker === segment.speaker) {
            lastSegment.text += ` ${ segment.text }`
            lastSegment.endTime = segment.endTime
            lastSegment.words = lastSegment.words.concat(segment.words)
        } else {
            chunkedSegments.push(segment)
        }
    }

    return chunkedSegments
}


/**
 * Parse transcripts generated by OpenAI's Whisper model and seed a Neo4j
 * database. Transcript data is searchable at the level of the statement so that
 * the frontend can jump directly to the relevant point in a matching video.
 * Granular statement-level data is also expected to seed a knowledge graph.
 * Structured at the statement level, this, too, will intertwingle the
 * narratives of a wide slate of interviewees for a deep account of an event.
 *
 * Whisper data has already been segmented by speaker and broken into
 * caption-sized hunks. The natural-language processing model attempts to keep
 * from splitting entities across captions, but it's not perfect: be on the
 * lookout for a class of bugs in which, e.g., "Stop the Church" is split into
 * "Stop the" and "Church," across captions, and does not match as a phrase.
 *
 * Edits to the captions for correctness and style will be made against the data
 * model, from which the captions are generated. The data model is the source of
 * truth, and the captions are a derived artifact.
 */
async function seed({ data, date, interviewee, interviewNumber, speakers, videoURL }) {
    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            MATCH (jim:Person {name: 'Jim Hubbard'})
            MATCH (sarah:Person {name: 'Sarah Schulman'})
            WITH jim, sarah
            CREATE (i:Interview {number: $interviewNumber, date: date($date), uid: $interviewUID, url: $interviewURL})
            CREATE (video:Video {url: $videoURL, uid: $videoUID})
            CREATE (interviewee:Person {name: $interviewee, uid: $intervieweeUID})
            CREATE (sarahSpeaker:Speaker:Interviewer {label: $speakers.sarah})
            CREATE (jimSpeaker:Speaker:Interviewer {label: $speakers.jim})
            CREATE (intervieweeSpeaker:Speaker:Interviewee {label: $speakers.interviewee})
            MERGE (interviewee)-[:INTERVIEWED_AS]->(intervieweeSpeaker)
            MERGE (jim)-[:INTERVIEWED_AS]->(jimSpeaker)
            MERGE (sarah)-[:INTERVIEWED_AS]->(sarahSpeaker)
            CREATE (i)-[:INTERVIEWED_WITH]->(intervieweeSpeaker)
            CREATE (i)-[:INTERVIEWED_WITH]->(jimSpeaker)
            CREATE (i)-[:INTERVIEWED_WITH]->(sarahSpeaker)
            CREATE (i)-[:HAS_VIDEO]->(video)
        `, {
            date,
            interviewNumber: int(interviewNumber),

            interviewee,
            speakers,
            interviewUID: nanoid(),
            intervieweeUID: nanoid(),
            interviewURL: videoURL,

            videoUID: nanoid(),
            videoURL,
        },
    )

    const speakerChunks = chunkBySpeaker(data.segments)
    for await (const chunk of speakerChunks) {
        const result: EagerResult = await neo4jDriver.executeQuery(
            // language=Cypher
            `
                MATCH (speaker:Speaker {label: $speaker}) <-[:INTERVIEWED_WITH]- (interview:Interview {number: $interviewNumber})
                MATCH (speaker) <-[:INTERVIEWED_AS]- (person:Person)
                CREATE (statement:Statement {text: $text}) -[:FROM_WORDS]-> (words:WordTimings {words: $words})
                MERGE (speaker)-[:SAYS {startTime: $startTime, endTime: $endTime}]->(statement)
                RETURN statement, person, interview, words
            `, {
                ...chunk,
                interviewNumber: int(interviewNumber),
            },
        )

        if (!result?.records?.length) {
            console.error(`
                Could not create node for segment starting ${ chunk.start } in interview
                ${ interviewNumber } for speaker ${ chunk.speaker }.

                ${ JSON.stringify(result, null, 2) }
            `)
        }
    }
}

async function bootstrap() {
    await neo4jDriver.getServerInfo()

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
          MATCH (n) DETACH DELETE n
        `,
    )

    await neo4jDriver.executeQuery(
    // language=Cypher
        `
          DROP INDEX transcript_search IF EXISTS
        `,
    )

    await neo4jDriver.executeQuery(
    // language=Cypher
        `
          DROP INDEX name_search IF EXISTS
        `,
    )

    for await (let label of NEO4J_LABELS) {
        await neo4jDriver.executeQuery(
            // language=Cypher
            `
                CREATE CONSTRAINT ${ label }UID IF NOT EXISTS
                FOR (n:${ label }) REQUIRE n.uid IS UNIQUE
            `,
            { label },
        )
    }

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            CREATE FULLTEXT INDEX transcript_search IF NOT EXISTS
            FOR (n:Statement) ON EACH [n.text]
        `)

    await neo4jDriver.executeQuery(
        // language=Cypher
        `
            CREATE (jim:Person {name: 'Jim Hubbard', uid: $jimUID})
            CREATE (sarah:Person {name: 'Sarah Schulman', uid: $sarahUID})
        `, { jimUID: nanoid(), sarahUID: nanoid() },
    )
}

async function main() {
    await bootstrap()


    let data


    // ~~~~~~~~~~~~~~~~~~~~~~ 002 - Robert Vasquez-Pacheco ~~~~~~~~~~~~~~~~~~~~~~ //
    data = JSON.parse(
        await fs.readFile(
            path.resolve(__dirname, '../assets/whisperx-subs/002.json'),
            'utf8',
        ),
    )

    await seed({
        data,
        date: '2002-12-14',
        interviewee: 'Robert Vasquez-Pacheco',
        interviewNumber: 2,
        speakers: {
            interviewee: 'SPEAKER_00',
            jim: 'SPEAKER_01',
            sarah: 'SPEAKER_02',
        },
        videoURL: '/interviews/002_robert_vasquez-pacheco.mp4',
    })
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //


    await neo4jDriver.close()
}

void (await main())
